version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bookmarks/manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookmarks:/app
    ports:
      - 8000:8000

  redis:
    image: redis
    ports:
      - 6379:6379
